### ISSUE TITLE
PHP Fatal Error: SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by hans2103** [wuunder/wuunder-webshopplugin-magento#4]
I'm receiving the following message per mail after a failing cron

> PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from '/LoginService.svc?wsdl' : failed to load external entity "/LoginService.svc?wsdl"
 in /data/web/source/public/vendor/wuunder/webshopplugin-magento/app/code/community/Wuunder/WuunderConnector/Model/Dpdwebservice.php on line 144

How can this be solved?

**Comment by timoj** [comment]
@hans2103 this is related to the dpd parcelshop picker. The error is a result of an invalid login at the dpd api. Which is correct since no credentials have been configured yet. Maybe this is a result of a test with the dpd parcelshop picker in the wuunder extension. Will pick this up with Giel.
